-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID,ANIMAL_OUTS.ANIMAL_TYPE,ANIMAL_OUTS.NAME
from ANIMAL_OUTS
left join ANIMAL_INS
on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
where (ANIMAL_INS.SEX_UPON_INTAKE='Intact Male' or ANIMAL_INS.SEX_UPON_INTAKE='Intact Female') and (ANIMAL_OUTS.SEX_UPON_OUTCOME='Neutered Male' or ANIMAL_OUTS.SEX_UPON_OUTCOME='Spayed Female')
order by ANIMAL_OUTS.ANIMAL_ID