SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
from ANIMAL_OUTS
left outer join ANIMAL_INS 
on ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
where isnull(ANIMAL_INS.ANIMAL_ID)=True
order by ANIMAL_OUTS.ANIMAL_ID